### ISSUE TITLE
Error opening the add menu - Anki 2.1.37

### ISSUE THREAD

**Issue by tiagooliveira5n** [ijgnd/anki21__editor_quick_note_and_deck_buttons#8]
Hello, how are you?
I updated the version of Anki and this error happened:

```
Anki 2.1.37 (6d596c8f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-12-17 10:21:28

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 35, in cmd
  File "aqt\webview.py", line 124, in _onCmd
  File "aqt\webview.py", line 569, in _onBridgeCmd
  File "aqt\toolbar.py", line 170, in _linkHandler
  File "aqt\toolbar.py", line 185, in _addLinkHandler
  File "aqt\main.py", line 1042, in onAddCard
  File "aqt\__init__.py", line 100, in open
  File "aqt\addcards.py", line 42, in __init__
  File "aqt\addcards.py", line 59, in setupChoosers
TypeError: init_mc() got an unexpected keyword argument 'on_activated'
```

**Comment by ijgnd** [comment]
Thanks for reporting this. I uploaded a new version to ankiweb for Anki 2.1.36+. Could you update, restart, and try again. If you still find problems let me know.

**Comment by tiagooliveira5n** [comment]
Thank you so much for the quick check!
Congratulations on the add-on.
